### ISSUE TITLE
Netcat or Socat

### ISSUE THREAD

**Issue by sarathkumar21** [microsoft/avml#12]
Is it possible to sent the memorydump via socat or netcat, without saving to disk directly ?

**Comment by bmc-msft** [comment]
There isn't built-in support to remotely capture memory without touching local disks, as this often leads to a less coherent snapshot due to the latencies involved.  That said, we have tested using `/dev/stdout` enable remote capture.

Example:
`ssh username@ip sudo avml --compress /dev/stdout > local-file.lime`

**Comment by sarathkumar21** [comment]
Thanks  /dev/stdout worked.
sudo ./avml  /dev/stdout | nc  <ip> <port> Server: nc -l -p <port> > output.lime

**Comment by sarathkumar21** [comment]
Thanks /dev/stdout worked with netcat
